config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"

  resources :products

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :cart, only: :index

  get "add_to_cart", to: "cart#add_to_cart"
  get "increase_to_cart", to: "cart#increase_quantity_cart"
  get "decrease_to_cart", to: "cart#decrease_quantity_cart"
  get "remove_to_cart", to: "cart#remove_to_cart"

  resources :orders do
    patch "cancel", to: "orders#cancel"
  end

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end
  end
  resources :feedbacks

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end

    resources :products
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include CartHelper

  before_action :logged_in_user
  before_action :load_product, only: %i(add_to_cart remove_to_cart
    decrease_quantity_cart increase_quantity_cart)
  after_action :total_price, only: %i(add_to_cart remove_to_cart
    decrease_quantity_cart increase_quantity_cart)
  before_action :load_product_in_cart, :total_price, only: :index
  before_action :check_quantity, only: :add_to_cart

  def index; end

  def add_to_cart
    session[:cart] ||= {}
    session[:cart][@product.id.to_s] ||= 0
    session[:cart][@product.id.to_s] += 1
    respond_to do |format|
      flash[:success] =
        t("add_to_cart_noti") + " #{view_context.link_to(t('shopping_cart'),
                                                         cart_index_path)}"
      format.html{redirect_to @product}
      format.js
    end
  end

  def increase_quantity_cart
    if session[:cart].key?(@product.id.to_s)
      session[:cart][@product.id.to_s] += 1
    else
      flash[:danger] = t("product_not_found_reload_page")
    end
    respond_to do |format|
      handle_quantity_warning

      format.html{redirect_to cart_index_path}
      format.js
    end
  end

  def decrease_quantity_cart
    if session[:cart].key?(@product.id.to_s)
      session[:cart][@product.id.to_s] -= 1
    else
      flash[:danger] = t("product_not_found_reload_page")
    end
    respond_to do |format|
      format.html{redirect_to cart_index_path}
      format.js
    end
  end

  def remove_to_cart
    session[:cart].delete(@product.id.to_s)

    respond_to do |format|
      format.html{redirect_to cart_index_path}
      format.js
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t("product_not_found")
    redirect_to root_url
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = t("please_log_in")
    store_location
    redirect_to login_url
  end

  def handle_quantity_warning
    return unless session[:cart][@product.id.to_s] == @product.quantity

    flash[:warning] = t("invalid_quantity")
  end

  def check_quantity
    return if @product.quantity.positive?

    flash[:danger] = t("out_of_stock")
    redirect_to @product
  end
end

app/helpers/cart_helper.rb
module CartHelper
  def load_product_in_cart
    @order = Order.new
    @cart = session[:cart] || {}
    @products = Product.find_id(@cart.keys)
  end

  def total_price
    @total_price = 0
    @cart = session[:cart] || {}
    @cart.each do |key, value|
      product = Product.find_by id: key
      if product
        @total_price += product.price * value
      else
        session[:cart].delete(key)
      end
    end
  end
end

app/views/cart/_cart_item.html.erb
<div class="row mb-4 d-flex justify-content-between align-items-center">
  <div class="col-md-2 col-lg-2 col-xl-2">
    <%= image_tag(product.image, alt: t("product_item"), class: "img-fluid rounded-3") %>
  </div>
  <div class="col-md-3 col-lg-3 col-xl-4">
    <h6 class="text-muted mb-3 fs-5"><%= product.category_name %></h6>
    <h6 class="text-black mb-0 fs-2"><%= product.name %></h6>
  </div>

  <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
    <% if (session[:cart][product.id&.to_s]) > 1 %>
      <%= form_tag decrease_to_cart_path, remote: true, method: :GET, class: "d-flex" do %>
        <%= hidden_field_tag :id, product.id %>
        <%= submit_tag "-", class: "btn btn-primary" %>
      <% end %>
    <% end %>
    <input readonly id="form1-quantity" min="0" name="quantity" value="<%= session[:cart][product.id.to_s] %>" type="number"
      class="form-control form-control-lg" />
    <% if (session[:cart][product.id.to_s]) < product.quantity %>
      <%= form_tag increase_to_cart_path, remote: true, method: :GET, class: "d-flex" do %>
        <%= hidden_field_tag :id, product.id %>
        <%= submit_tag "+", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-3 col-lg-2 col-xl-1 offset-lg-1">
    <h6 class="mb-0 fs-4"><%= product.price * session[:cart][product.id.to_s] %></h6>
  </div>
    <div class="col-md-1 col-lg-1 col-xl-1 text-end fs-3">

      <%= form_tag remove_to_cart_path, remote: true, method: :GET, class: "d-flex" do %>
        <%= hidden_field_tag :id, product.id %>
        <%= submit_tag "X", class: "btn btn-danger" %>
      <% end %>

    </div>
</div>
<hr class="my-4">

app/views/cart/index.html.erb
<section class="h-100 h-custom" style="background-color: #d2c9ff;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                    <h1 class="fw-bold mb-0 text-black"><%= t("shopping_cart") %></h1>
                  </div>
                  <hr class="my-4">
                  <%= render(partial: "cart/cart_item", collection: @products, as: :product) || t("no_product_display") %>
                  <div class="pt-5">
                    <%= link_to root_path, class: "text-decoration-none text-secondary" do %>
                      <h6 class="mb-0 fs-4 fw-bold">
                        <i class="fas fa-long-arrow-alt-left me-2"></i><%= t("back_to_shop") %>
                      </h6>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 bg-grey">
                <div class="p-5">
                  <h3 class="fw-bold mb-5 mt-2 pt-1"><%= t("bill") %></h3>
                  <hr class="my-4">
                  <div class="d-flex justify-content-between mb-4">
                    <h5 class="text-uppercase">
                      <%= t("items") %>
                      <%= session[:cart]&.length %>
                    </h5>
                  </div>
                  <hr class="my-4">

                  <div class="d-flex justify-content-between mb-5">
                    <h5 class="text-uppercase fs-3"><%= t("total_price") %></h5>
                    <h5 class="fs-3"><%= @total_price %></h5>
                  </div>
                  <% if logged_in? && session[:cart]&.empty? == false %>
                    <%= render "orders/form_order" %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>