config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"

  resources :products

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :cart, only: :index

  get "add_to_cart", to: "cart#add_to_cart"
  get "increase_to_cart", to: "cart#increase_quantity_cart"
  get "decrease_to_cart", to: "cart#decrease_quantity_cart"
  get "remove_to_cart", to: "cart#remove_to_cart"

  resources :orders do
    patch "cancel", to: "orders#cancel"
  end

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end
  end
  resources :feedbacks

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end

    resources :products
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy

  enum status: {awaiting: 1, confirmed: 2, canceled: 3}
  delegate :name, :email, to: :user, prefix: true

  validates :reciver_name, presence: true,
    length: {maximum: Settings.orders.length_30}
  validates :reciver_address, presence: true,
    length: {maximum: Settings.orders.length_50}
  validates :reciver_phone, presence: true,
    format: {with: Settings.orders.regex}

  delegate :name, to: :user, prefix: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :is_admin?
  before_action :load_order, only: %i(confirm cancel reason)
  before_action :check_status, only: %i(confirm cancel)

  def index
    @pagy, @orders = pagy(Order.newest, items: Settings.orders.number_of_page_5)
  end

  def confirm
    if @order.confirmed!
      UserMailer.confirm_order(@order).deliver_now
      redirect_to admin_orders_path, notice: t("order_has_been_confirmed")
    else
      flash[:notice] = t("error")
      render "admin/orders/index", status: :unprocessable_entity
    end
  end

  def reason; end

  def cancel
    ActiveRecord::Base.transaction do
      if params[:reason].present?
        @order.canceled!
        return_quantity_products @order
        UserMailer.cancel_order(@order, params[:reason]).deliver_now
        redirect_to admin_orders_path, notice: t("order_has_been_cancelled")
      else
        flash[:danger] = t("enter_reason")
        render "admin/orders/reason", status: :unprocessable_entity
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:notice] = t("error")
    render "admin/orders/index", status: :unprocessable_entity
  end

  private
  def is_admin?
    return if current_user.is_admin

    redirect_to root_path
    flash[:danger] = t("not_admin")
  end

  def load_order
    @order = Order.find_by id: params[:order_id]
    return if @order

    flash[:danger] = t("order_not_found")
    redirect_to root_url
  end

  def return_quantity_products order
    @order_details = order.order_details

    @order_details.each do |order_detail|
      order_detail.product.quantity += order_detail.quantity_product
      order_detail.product.save!
    end
  end

  def check_status
    return if @order.awaiting?

    flash[:danger] = t("can_not_update_order")
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CartHelper
  before_action :logged_in_user
  before_action :load_product_in_cart, :total_price, only: :create
  before_action :load_order, only: %i(show cancel)
  before_action :correct_user, only: :cancel

  def index
    @orders = current_user.orders.includes(:order_details).newest
  end

  def show; end

  def create
    ActiveRecord::Base.transaction do
      @order = current_user.orders.build order_params
      @order.save!
      create_order_detail @order
      update_quantity_products
    end
    clear_cart
    HardJob.perform_async @order.id
    flash[:success] = t("success")
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid
    flash[:notice] = t("error")
    render "cart/index", status: :unprocessable_entity
  end

  def cancel
    ActiveRecord::Base.transaction do
      @order.canceled!
      return_quantity_products @order
      redirect_to orders_path, notice: t("order_has_been_cancelled")
    end
  rescue ActiveRecord::RecordInvalid
    flash[:notice] = t("error")
    render "orders/index", status: :unprocessable_entity
  end
  private
  def clear_cart
    session[:cart].clear
  end

  def order_params
    extracted_params = params.require(:order).permit(
      :reciver_name,
      :reciver_address,
      :reciver_phone,
      :status
    )
    extracted_params[:total_price] = @total_price
    extracted_params
  end

  def load_order
    @order = Order.includes(:order_details).find_by id: params[:id] || params[:order_id]
    return if @order

    flash[:danger] = t("order_not_found")
    redirect_to root_url
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = t("please_log_in")
    store_location
    redirect_to login_url
  end

  def create_order_detail order
    keys_session = session[:cart]&.keys&.map(&:to_i)
    @products = Product.find_id keys_session
    @order_details = []
    @products.each do |product|
      order_detail = OrderDetail.new(
        product:,
        order:,
        price_product: product.price,
        quantity_product: session[:cart][product.id.to_s]
      )
      @order_details << order_detail
    end
    @order_details.each(&:save!)
  end

  def update_quantity_products
    keys_session = session[:cart]&.keys&.map(&:to_i)
    @products = Product.find_id keys_session
    @products.each do |product|
      product.quantity = product.quantity - session[:cart][product.id.to_s]
    end
    @products.each(&:save!)
  end

  def return_quantity_products order
    @order_details = order.order_details
    @order_details.each do |order_detail|
      order_detail.product.quantity += order_detail.quantity_product
      order_detail.product.save!
    end
  end

  def correct_user
    @order = current_user.orders.find_by id: params[:order_id]
    return if @order

    flash[:danger] = t("order_invalid")
    redirect_to request.referer || root_url
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<section class="h-100 h-custom" style="background-color: #d2c9ff;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                    <h1 class="fw-bold mb-0 text-black"><%= t("orders_management") %></h1>
                  </div>
                  <hr class="my-4">

                  <table class="table table-striped table-hover">
                    <thead class="bg-light">
                      <tr class="fs-4">
                        <th class="px-3 py-4">#</th>
                        <th class="px-3 py-4"><%= t("customer") %></th>
                        <th class="px-3 py-4"><%= t("product_quantity") %></th>
                        <th class="px-3 py-4"><%= t("total_price") %></th>
                        <th class="px-3 py-4"><%= t("status") %></th>
                        <th class="px-3 py-4"><%= t("date_time_order") %></th>
                        <th class="px-3 py-4"></th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @orders.each_with_index do |order, index| %>
                      <tr class="fs-5">
                        <td class="px-3 py-5"><%= index + 1 %></td>
                        <td class="px-3 py-5"><%= order.user.name %></td>
                        <td class="px-3 py-5 ps-5"><%= order.order_details.length %></td>
                        <td class="px-3 py-5"><%= order.total_price %></td>
                        <td class="px-3 py-5 fw-bold text-<%=order.status%>"><%= t("#{order.status}")%></td>
                        <td class="px-3 py-5"><%= order.created_at %></td>
                        <td class="px-3 py-5 text-center">
                          <div class="d-grid gap-2 d-md-block">
                            <%= link_to order, class: "text-decoration-none" do %>
                              <button type="button" class="btn btn-lg btn-warning text-white fw-normal text-uppercase"><%= t("details") %></button>
                            <% end %>
                            <% if order.awaiting? %>
                              <%= link_to admin_order_confirm_path(order), data: { "turbo-method": :patch}, class: "text-decoration-none" do %>
                                <button type="button" class="btn btn-lg btn-primary text-white fw-normal text-uppercase"><%= t("confirm") %></button>
                              <% end %>
                              <%= link_to admin_order_reason_path(order), data: { "turbo-method": :get}, class: "text-decoration-none" do %>
                                <button type="button" class="btn btn-lg btn-danger text-white fw-normal text-uppercase"><%= t("cancel") %></button>
                              <% end %>
                            <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                    </tbody>
                    <%== pagy_bootstrap_nav(@pagy) %>
                  </table>
                  <%== pagy_bootstrap_nav(@pagy) %>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/orders/reason.html.erb
<section class="h-100 h-custom" style="background-color: #d2c9ff;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="p-5">

                  <div class="row justify-content-center p-5 m-5">
                    <div class="col-md-6 col-md-offset-3 login__form">
                      <div class="d-flex align-items-center">
                        <%= link_to admin_orders_path, class: "text-decoration-none" do %>
                          <i class="fa-solid fa-arrow-left fs-1 me-4 text-black"></i>
                        <% end %>
                        <h1 class="text-black fw-medium"><%= t("cancel_order_confirmation") %></h1>
                      </div>
                        <%= form_tag admin_order_cancel_path, remote: true, method: :PATCH, class: "reason_form" do %>
                          <%= hidden_field_tag :order_id, @order.id %>
                          <%= label_tag :reason, "#{t("reason_order_cancellation")} :", class: "d-block py-2 fs-4" %>
                          <%= text_area_tag :reason %>
                          <%= submit_tag t("cancel"), class: "btn btn-danger fs-4 px-5 py-3 mt-3" %>
                        <% end %>
                    </div>
                  </div>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>