config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"

  resources :products

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :cart, only: :index

  get "add_to_cart", to: "cart#add_to_cart"
  get "increase_to_cart", to: "cart#increase_quantity_cart"
  get "decrease_to_cart", to: "cart#decrease_quantity_cart"
  get "remove_to_cart", to: "cart#remove_to_cart"

  resources :orders do
    patch "cancel", to: "orders#cancel"
  end

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end
  end
  resources :feedbacks

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end

    resources :products
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  has_many :feedbacks, dependent: :destroy

  delegate :name, to: :category, prefix: true

  validates :name, presence: true,
                  length: {maximum: Settings.products.length_30}
  validates :price, presence: true, numericality: {
    less_than_or_equal_to: Settings.products.limit_price
  }
  validates :quantity, presence: true, numericality: {
    less_than_or_equal_to: Settings.products.limit_quantity
  }
  validates :description, presence: true,
                  length: {maximum: Settings.products.length_30}
  validates :category_id, presence: true

  scope :sort_by_name, ->{order :name}
  scope :search_by_name, lambda {|name|
                           where("name LIKE ?", "%#{name}%")
                         }
  scope :filter_by_category_id, lambda {|category_id|
                                  where(category_id:)
                                }
  scope :find_id, lambda {|id|
                    where(id:)
                  }
  def self.ransackable_attributes _auth_object = nil
    %w(name description)
  end
  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :load_info_categories,
                only: %i(show index new create edit update)
  before_action :load_product, only: %i(show edit update)
  before_action :load_category, only: :create
  before_action :admin_user, only: %i(index new create edit update)

  def index
    @pagy, @products = pagy(Product.newest,
                            items: Settings.orders.number_of_page_5)
  end

  def show
    @feedbacks = @product.feedbacks.newest
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = @category.products.build product_params
    if @product.save
      flash[:success] = t("success")
      redirect_to admin_products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update product_params
      flash[:success] = t("product_updated")
      redirect_to admin_products_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price,
                                    :description, :quantity, :rating, :image)
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t("product_not_found")
    redirect_to root_url
  end

  def load_category
    @category = Category.find_by id: params[:product][:category_id]
    return if @category

    flash[:danger] = t("category_not_found")
    redirect_to root_url
  end

  def admin_user
    return if current_user&.is_admin?

    redirect_to root_path
    flash[:alert] = t("not_permission")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_info_categories, only: %i(show index)
  before_action :load_product, only: %i(show)
  before_action :admin_user, :load_category, only: %i(new create)

  def show
    @feedbacks = @product.feedbacks.newest
  end

  def new
    @product = Product.new
  end

  def index
    if params[:q].present?
      search_by_name
    elsif params[:id].present?
      search_by_category
    else
      default_search
    end
    render "static_pages/home"
  end

  private

  def product_params
    params.require(:product).permit(:name, :price,
                                    :description, :quantity, :rating, :image)
  end

  def search_by_name
    @q = Product.ransack(params[:q])
    search_results = @q.result
    @pagy, @products = pagy(search_results,
                            items: Settings.products.number_of_page_10)
  end

  def search_by_category
    @children_categories = Category.find_id_or_parent(params[:id])
    children_category_id = @children_categories.pluck(:id)
    search_results = if @children_categories.length == 1
                       Product.filter_by_category_id(params[:id])
                     else
                       Product.filter_by_category_id(children_category_id)
                     end
    @pagy, @products = pagy(search_results,
                            items: Settings.products.number_of_page_10)
  end

  def default_search
    search_results = Product.all
    @pagy, @products = pagy(search_results,
                            items: Settings.products.number_of_page_10)
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t("product_not_found")
    redirect_to root_url
  end

  def admin_user
    return if current_user&.is_admin?

    redirect_to root_path
    flash[:alert] = t("not_permission")
  end

  def load_category
    category_search = Category.search_by_name(params[:name])
    @category = Category.find_id(category_search.pluck(:id))
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<section class="h-100 h-custom" style="background-color: #D2C9FF;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="row justify-content-center p-5 m-5">
                    <div class="col-md-6 col-md-offset-3 login__form">
                      <div class="d-flex align-items-center">
                        <%= link_to admin_products_path, class: "text-decoration-none" do %>
                          <i class="fa-solid fa-arrow-left fs-1 me-4 text-black"></i>
                        <% end %>
                        <h1 class="text-black fw-medium"><%= t("edit_product") %></h1>
                      </div>
                      <%= image_tag(@product.image, alt: t("product_item"), class: "img-fluid rounded-3 ad_image_products w-50") %>
                      <div class="row">
                        <div class="col-md-12 col-md-offset-3 order__form">
                          <%= form_for @product, url: { action: "update" }, namespace: "admin"  do |f| %>
                            <%= render "shared/error_messages", object: f.object %>
                            <%= f.label :name, class: "fs-4 mt-3 mb-2" %><%= f.text_field :name, class: "form-control" %>
                            <%= f.label :price, class: "fs-4 mt-3 mb-2" %><%= f.text_field :price, class: "form-control" %>
                            <%= f.label :quantity, class: "fs-4 mt-3 mb-2" %><%= f.text_field :quantity, class: "form-control" %>
                            <%= f.hidden_field :rating, value: 0 %>
                            <%= f.label :description, class: "fs-4 mt-3 mb-2" %><%= f.text_area :description, class: "form-control" %>
                            <%= f.hidden_field :category_id, value: 0 %>
                            <%= f.label :category, class: "fs-4 mt-3 mb-2" %>
                            <%# <%= f.collection_select :category_id, @children_childrens, :id, :name, { }, { class: "form-control" } %>
                            <div class="menu__right-category px-2 d-flex justify-content-center">
                              <% @childrens.each do |children| %>
                                <ul class="mx-5"><%=  children.name%>
                                  <% @children_childrens.each do |children_children| %>
                                    <% if children.id == children_children.parent_id %>
                                      <li class="py-3"><%= f.radio_button :category_id, children_children.id %> <%= children_children.name %></li>
                                    <% end %>
                                  <% end %>
                                </ul>
                              <% end %>
                            </div>
                            <%= f.label :image, class: "fs-4 mt-3 mb-2" %>
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", class: "form-control" %>
                            <%= f.submit t("edit"), class: "btn btn-primary mt-4 order__btn" %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/products/index.html.erb
<section class="h-100 h-custom" style="background-color: #d2c9ff;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                    <h1 class="fw-bold mb-0 text-black">Quản lý sản phẩm</h1>
                    <%= link_to new_admin_product_path, class: "text-decoration-none" do %>
                      <button type="button" class="btn btn-lg btn-success text-white fw-normal text-uppercase"><%= t("add_new_product") %></button>
                    <% end %>
                  </div>
                  <hr class="my-4">

                  <table class="table table-striped table-hover">
                    <thead class="bg-light">
                      <tr class="fs-4">
                        <th class="px-3 py-4">#</th>
                        <th class="px-3 py-4"><%= t("product_name") %></th>
                        <th class="px-3 py-4"><%= t("image") %></th>
                        <th class="px-3 py-4"><%= t("price") %></th>
                        <th class="px-3 py-4"><%= t("product_description") %></th>
                        <th class="px-3 py-4"><%= t("quantity") %></th>
                        <th class="px-3 py-4"><%= t("rating") %></th>
                        <th class="px-3 py-4"><%= t("category") %></th>
                        <th class="px-3 py-4"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @products.each_with_index do |product, index| %>
                        <tr class="fs-5">
                          <td class="px-3 py-5"><%= index + 1 %></td>
                          <td class="px-3 py-5"><%= product.name %></td>

                          <td class="px-3 py-5">
                            <%= image_tag(product.image, alt: t("product_item"), class: "ad_image_products") %>
                          </td>

                          <td class="px-3 py-5"><%= product.price %></td>
                          <td class="px-3 py-5"><%= product.description %></td>
                          <td class="px-3 py-5"><%= product.quantity %></td>
                          <td class="px-3 py-5"><%= product.rating %></td>
                          <td class="px-3 py-5"><%= product.category.name %></td>

                          <td class="px-3 py-5 text-center">
                            <div class="d-grid gap-2 d-md-block">
                              <%= link_to product, class: "text-decoration-none" do %>
                                <button type="button" class="btn btn-lg btn-warning text-white fw-normal text-uppercase"><%= t("details") %></button>
                              <% end %>
                              <%= link_to edit_admin_product_path(product), class: "text-decoration-none" do %>
                                <button type="button" class="btn btn-lg btn-primary text-white fw-normal text-uppercase"><%= t("edit") %></button>
                              <% end %>
                              <%= link_to product, data: {"turbo-method": :delete, turbo_confirm: "You sure?"}, class: "text-decoration-none" do %>
                                <button type="button" class="btn btn-lg btn-danger text-white fw-normal text-uppercase"><%= t("delete") %></button>
                              <% end %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                    <%== pagy_bootstrap_nav(@pagy) %>
                  </table>
                  <%== pagy_bootstrap_nav(@pagy) %>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/products/new.html.erb
<section class="h-100 h-custom" style="background-color: #d2c9ff;">
  <div class="container py-5 h-100 cart__container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-12">
                <div class="p-5">

                  <div class="row justify-content-center p-5 m-5">
                    <div class="col-md-6 col-md-offset-3 login__form">
                      <div class="d-flex align-items-center">
                        <%= link_to admin_orders_path, class: "text-decoration-none" do %>
                          <i class="fa-solid fa-arrow-left fs-1 me-4 text-black"></i>
                        <% end %>
                        <h1 class="text-black fw-medium"><%= t("add_new_product") %></h1>
                      </div>

                      <div class="row">
                        <div class="col-md-12 col-md-offset-3 order__form">
                          <%= form_for @product, url: { action: "create" }, namespace: "admin"  do |f| %>
                            <%= render "shared/error_messages", object: f.object %>
                            <%= f.label :name, class: "fs-4 mt-3 mb-2" %><%= f.text_field :name, class: "form-control" %>
                            <%= f.label :price, class: "fs-4 mt-3 mb-2" %><%= f.text_field :price, class: "form-control" %>
                            <%= f.label :quantity, class: "fs-4 mt-3 mb-2" %><%= f.text_field :quantity, class: "form-control" %>
                            <%= f.hidden_field :rating, value: 0 %>
                            <%= f.label :description, class: "fs-4 mt-3 mb-2" %><%= f.text_area :description, class: "form-control" %>
                            <%= f.hidden_field :category_id, value: 0 %>

                            <%= f.label :category, class: "fs-4 mt-3 mb-2" %>

                            <%# <%= f.collection_select :category_id, @children_childrens, :id, :name, { }, { class: "form-control" } %>

                            <div class="menu__right-category px-2 d-flex justify-content-center">
                              <% @childrens.each do |children| %>
                                <ul class="mx-5"><%=  children.name%>
                                  <% @children_childrens.each do |children_children| %>
                                    <% if children.id == children_children.parent_id %>
                                      <li class="py-3"><%= f.radio_button :category_id, children_children.id %> <%= children_children.name %></li>
                                    <% end %>
                                  <% end %>
                                </ul>
                              <% end %>
                            </div>

                            <%= f.label :image, class: "fs-4 mt-3 mb-2" %>
                            <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", class: "form-control" %>
                            <%= f.submit t("create"), class: "btn btn-primary mt-4 order__btn" %>
                          <% end %>
                        </div>
                      </div>

                    </div>
                  </div>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>