config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"

  resources :products

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  resources :cart, only: :index

  get "add_to_cart", to: "cart#add_to_cart"
  get "increase_to_cart", to: "cart#increase_quantity_cart"
  get "decrease_to_cart", to: "cart#decrease_quantity_cart"
  get "remove_to_cart", to: "cart#remove_to_cart"

  resources :orders do
    patch "cancel", to: "orders#cancel"
  end

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end
  end
  resources :feedbacks

  namespace :admin do
    resources :orders, only: :index do
      patch "confirm", to: "orders#confirm"
      patch "cancel", to: "orders#cancel"
      get "reason", to: "orders#reason"
    end

    resources :products
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="footer">
    <div class="grid">
        <div class="grid__row">
            <div class="col-6 p_left">
                <h3 class="footer-label"><%= t("about_us") %></h3>
                <div class="footer-link">
                    <a href=""><%= t("clothing_and_fashion_accessories_shop") %></a>
                    <a href=""> <%= t("address") %>: 16 Ly Thuong Kiet</a>
                </div>
            </div>
            <div class="col-6 p_left">
                <h3 class="footer-label"><%= t("contact") %></h3>
                <div class="footer-link">
                    <a href=""> <%= t("phone") %>: 0889152558</a>
                    <a href=""> <%= t("email") %>: shopquanao@gmail.com</a>
                </div>
            </div>
            <div class="footer-footer">
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<!-- Header -->
<div class="header__fixed">
  <div class="header">
    <div class="grid">
      <div class="header__content">
        <div class="header__left">
          <%= link_to root_path, class: "text-decoration-none" do %>
            <%= image_tag("logos/logo7.png", :alt => "Header logo", :class => "header__left-logo") %>
          <% end %>
        </div>
        <div class="fs-3">
            <%= link_to "En", locale:"en" %> |
            <%= link_to "Vi", locale:"vi" %>
          </div>
        <div class="header__right">
          <% if logged_in? %>
            <%= link_to cart_index_path, class: "text-decoration-none" do %> 
              <% if session.has_key?(:cart) && !session[:cart].empty? %>
                <span class="cart__quantity"><%= session[:cart]&.length %></span>
              <% end %>
              <%= image_tag("logos/logo2.png", :alt => "Cart", id: "cart", :class => "user_menu_logo me-3") %>
            <% end %>
            <%= image_tag("logos/account.png", :alt => "User menu", id: "account", :class => "user_menu_logo") %>
          <% else %>
            <%= link_to t("log_in"), login_path, class: "fs-4" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- Nav -->
  <div class="nav">
    <ul class="nav-menu">
      <li class="nav-menu-item text-uppercase"><%= t("about_us") %></li>
      <li class="nav-menu-item text-uppercase"><%= t("products") %></li>
      <li class="nav-menu-item text-uppercase"><%= t("contact") %></li>
      <li class="nav-menu-item text-uppercase"><%= t("support") %></li>
    </ul>
  </div>
</div>

app/views/layouts/_home_categories.html.erb
<div class="menu__right h-98">
  <div class="menu__right-header">
    <h3><%= t("categories") %></h3>
  </div>
  <div class="menu__right-category px-2">
    <% @childrens.each do |children| %>
      <ul class="text-danger fs-2 fw-bold px-5"> <%= link_to children.name, products_path(id: children.id), class: "text-decoration-none text-danger" %>
        <% @children_childrens.each do |children_children| %>
          <% if children.id == children_children.parent_id %>
            <li class="menu__right-category-item fs-3 fw-normal"><%= link_to children_children.name, products_path(id: children_children.id), class: "text-decoration-none menu__right-category-item" %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_main_slider.html.erb
<!-- Slider -->
<div class="">
    <div class="slider">
    </div>
</div>

app/views/layouts/_user_menu.html.erb
<!-- user menu -->
<% if logged_in? %>
    <div class="user-menu " id="user-menu">
        <div class="btn-close">
            <%= image_tag("icon/close.png", :alt => "Close", :id => "btnClose") %>
        </div>
        <div class="user-menu-profile">
            <%= image_tag("icon/avatar1.png", :alt => "Avater user") %>
            <Span class="user-name"><%= @current_user.name %></Span>
        </div>
        <hr>
        <div class="user-menu-list">
            <div class="user-menu-list-item">
                <%= image_tag("icon/home.png", :alt => "") %>
                <span><%= t("home") %></span>
            </div>
            <hr>
            <%= link_to orders_path, class: "text-decoration-none" do %>
                <div class="user-menu-list-item">
                    <%= image_tag("icon/list.PNG", :alt => "") %>
                    <span><%= t("my_order") %></span>
                </div>
            <% end %>
            <hr>
            <% if current_user.is_admin %>
                <%= link_to admin_orders_path, class: "text-decoration-none" do %>
                    <div class="user-menu-list-item">
                        <%= image_tag("icon/favourite.PNG", :alt => "") %>
                        <span><%= t("orders_management") %></span>
                    </div>
                <% end %>
                <hr>
                 <%= link_to admin_products_path, class: "text-decoration-none" do %>
                    <div class="user-menu-list-item">
                        <%= image_tag("icon/favourite.PNG", :alt => "") %>
                        <span><%= "Quản lý sản phẩm" %></span>
                    </div>
                <% end %>
                <hr>
            <% end %>
            <div class="user-menu-list-item">
                <%= image_tag("icon/logout.PNG", :alt => "") %>
                <span><%= link_to t("log_out"),logout_path, data: { "turbo-method": :delete } %></span>
            </div>

        </div>
    </div>
<% end %>
    <!-- end user menu -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="application">
      <% flash.each do |message_type, message| %>
        <div class="fs-4 alert alert-<%= message_type %>">
          <%= message.html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= render "layouts/user_menu" %>

    <%= javascript_include_tag "jquery.min" %>
    <%= javascript_include_tag "bootstrap.min" %>
  </body>
</html>